### ISSUE TITLE
SpotAgentNodesStack Template error: Unable to get mapping for K8sVersionMap::1.13::STD

### ISSUE THREAD

**Issue by gsf** [aws-quickstart/quickstart-cloudbees-core#14] opened 2019-07-30 21:31 UTC
When deploying to a fresh VPC I get this error in SpotAgentNodesStack:

    Template error: Unable to get mapping for K8sVersionMap::1.13::STD

It looks like 1.13 needs to be added to the mapping below, and 1.10 should be dropped since it's no longer supported in the amazon-eks-nodegroup template.

https://github.com/aws-quickstart/quickstart-cloudbees-core/blob/3c13ac9a7514691b166d727971761c5f21713603/templates/cloudbees-core-spot-nodes.template.yaml#L439-L448.

**Comment by schottsfired** [comment] 2019-07-30 22:18
Hi @gsf, thanks so much for reporting the issue! I just discovered it myself a few hours ago, and I've filed a pull request that fixes it.

**Comment by schottsfired** [comment] 2019-07-30 22:45
@gsf the pull request has been merged. Can you confirm this is no longer an issue?

Thanks

**Comment by schottsfired** [comment] 2019-07-31 02:33
Hi @gsf, the fix should be live now. Can you confirm that the issue is resolved? Thanks!

**Comment by schottsfired** [comment] 2020-03-08 20:37
Hi @jaymccon can we close this issue? I failed to commit AMI mappings for the Spot node pool while upgrading to K8s 1.13. We are on K8s 1.14 now and there are no issues.

**Comment by gsf** [comment] 2020-03-10 16:12
Sorry I failed to follow up. This did resolve our issue. Thanks for the quick fix.

**Closed** 2020-03-10 20:12 UTC
